/** Query key factory. Every cache entry in the app is addressed through here. */
export const qk = {
  me: () => ["me"] as const,
  workspaces: () => ["workspaces"] as const,
  workspace: (slug: string) => ["workspace", slug] as const,
  wsMembers: (slug: string) => ["workspace", slug, "members"] as const,
  invites: (slug: string) => ["workspace", slug, "invites"] as const,
  roles: (slug: string) => ["workspace", slug, "roles"] as const,
  catalogue: () => ["permissions"] as const,
  wsActivity: (slug: string) => ["workspace", slug, "activity"] as const,
  myTasks: (slug: string) => ["workspace", slug, "my-tasks"] as const,
  audit: (slug: string) => ["workspace", slug, "audit"] as const,
  directory: (slug: string) => ["workspace", slug, "directory"] as const,
  search: (slug: string, q: string, types?: string) => ["workspace", slug, "search", q, types ?? "all"] as const,
  recents: () => ["recents"] as const,

  projects: (slug: string) => ["workspace", slug, "projects"] as const,
  project: (slug: string, key: string) => ["project", slug, key.toUpperCase()] as const,
  /** Everything scoped to one project id (for blanket invalidation). */
  scope: (projectId: string) => ["p", projectId] as const,
  statuses: (projectId: string) => ["p", projectId, "statuses"] as const,
  labels: (projectId: string) => ["p", projectId, "labels"] as const,
  members: (projectId: string) => ["p", projectId, "members"] as const,
  accessRequests: (projectId: string) => ["p", projectId, "access-requests"] as const,
  summary: (projectId: string) => ["p", projectId, "summary"] as const,
  activity: (projectId: string) => ["p", projectId, "activity"] as const,
  board: (projectId: string, sprint = "active") => ["p", projectId, "board", sprint] as const,
  backlog: (projectId: string) => ["p", projectId, "backlog"] as const,
  taskList: (projectId: string) => ["p", projectId, "tasks"] as const,
  objectives: (projectId: string) => ["p", projectId, "objectives"] as const,
  milestones: (projectId: string) => ["p", projectId, "milestones"] as const,
  epics: (projectId: string) => ["p", projectId, "epics"] as const,
  sprints: (projectId: string) => ["p", projectId, "sprints"] as const,
  reports: (projectId: string, kind: string, ...args: (string | undefined)[]) => ["p", projectId, "reports", kind, ...args] as const,

  task: (slug: string, key: string) => ["task", slug, key.toUpperCase()] as const,
  comments: (taskId: string) => ["t", taskId, "comments"] as const,
  attachments: (taskId: string) => ["t", taskId, "attachments"] as const,
  taskActivity: (taskId: string) => ["t", taskId, "activity"] as const,

  notifications: (tab: string, workspaceId?: string) => ["notifications", workspaceId ?? "all", tab] as const,
  unread: (workspaceId?: string) => ["notifications", workspaceId ?? "all", "unread"] as const,
  prefs: () => ["notification-prefs"] as const,
};
