# Generated by Django 5.2.18 on 2026-10-09 06:56

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_savedview_viewpin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("select", "Select"),
                            ("date", "Date"),
                            ("user", "Person"),
                        ],
                        max_length=8,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomFieldOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("color", models.CharField(max_length=24)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="projects.customfield",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="customfield",
            index=models.Index(
                fields=["project", "position"], name="custom_field_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="customfield",
            constraint=models.UniqueConstraint(
                models.F("project"),
                django.db.models.functions.text.Lower("name"),
                name="custom_field_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldoption",
            index=models.Index(
                fields=["field", "position"], name="custom_field_option_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldoption",
            constraint=models.UniqueConstraint(
                models.F("field"),
                django.db.models.functions.text.Lower("name"),
                name="custom_field_option_unique",
            ),
        ),
    ]
