# Generated by Django 5.2.18 on 2026-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("assigned", "assigned"),
                    ("mention", "mention"),
                    ("status", "status"),
                    ("comment", "comment"),
                    ("due", "due"),
                    ("sprint", "sprint"),
                    ("access", "access"),
                ],
                max_length=16,
            ),
        ),
    ]
