# Generated by Django 5.2.18 on 2026-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_access_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("assigned", "assigned"),
                    ("mention", "mention"),
                    ("status", "status"),
                    ("comment", "comment"),
                    ("due", "due"),
                    ("sprint", "sprint"),
                    ("access", "access"),
                    ("import", "import"),
                ],
                max_length=16,
            ),
        ),
    ]
