# Generated by Django 5.2.18 on 2026-10-07 18:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_name", models.CharField(blank=True, default="", max_length=80)),
                ("action", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_id", models.CharField(blank=True, default="", max_length=64)),
                ("entity_key", models.CharField(blank=True, max_length=40, null=True)),
                ("target", models.CharField(blank=True, default="", max_length=300)),
                ("task_key", models.CharField(blank=True, max_length=40, null=True)),
                ("task_title", models.CharField(blank=True, max_length=300, null=True)),
                ("changes", models.JSONField(blank=True, default=list)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(default="web", max_length=8)),
                ("request_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "-created_at"], name="audit_ws_created"
                    ),
                    models.Index(
                        fields=["workspace", "actor", "-created_at"],
                        name="audit_ws_actor",
                    ),
                ],
            },
        ),
    ]
