# Generated by Django 5.2.18 on 2026-10-09 10:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_custom_fields"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PresenceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.UUIDField()),
                (
                    "location_kind",
                    models.CharField(
                        choices=[
                            ("board", "Board"),
                            ("dashboard", "Dashboard"),
                            ("task", "Task"),
                        ],
                        max_length=10,
                    ),
                ),
                ("location_id", models.UUIDField()),
                ("private", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[("viewing", "Viewing"), ("editing", "Editing")],
                        default="viewing",
                        max_length=8,
                    ),
                ),
                ("field", models.CharField(blank=True, max_length=48, null=True)),
                ("typing_until", models.DateTimeField(blank=True, null=True)),
                ("since", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "expires_at"], name="presence_project_expiry"
                    ),
                    models.Index(
                        fields=["location_kind", "location_id"],
                        name="presence_location",
                    ),
                    models.Index(fields=["expires_at"], name="presence_expiry"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "session_id"),
                        name="presence_user_session_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RealtimeEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=32)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["workspace", "id"], name="rt_event_ws_id"),
                    models.Index(fields=["created_at"], name="rt_event_created"),
                ],
            },
        ),
    ]
