# Generated by Django 5.2.18 on 2026-10-09 06:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_initial"),
        ("projects", "0003_custom_fields"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskFieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "number",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="time_estimate_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("time_estimate_minutes__lte", 60000)),
                name="task_time_estimate_range",
            ),
        ),
        migrations.AddField(
            model_name="taskdependency",
            name="blocked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_by_links",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskdependency",
            name="blocker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks_links",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskdependency",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskdependency",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="taskfieldvalue",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="projects.customfield",
            ),
        ),
        migrations.AddField(
            model_name="taskfieldvalue",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="projects.customfieldoption",
            ),
        ),
        migrations.AddField(
            model_name="taskfieldvalue",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_values",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskfieldvalue",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="taskdependency",
            constraint=models.UniqueConstraint(
                fields=("blocker", "blocked"), name="task_dependency_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskdependency",
            constraint=models.CheckConstraint(
                condition=models.Q(("blocker", models.F("blocked")), _negated=True),
                name="task_dependency_not_self",
            ),
        ),
        migrations.AddIndex(
            model_name="taskfieldvalue",
            index=models.Index(fields=["field", "option"], name="field_value_option"),
        ),
        migrations.AddIndex(
            model_name="taskfieldvalue",
            index=models.Index(fields=["field", "user"], name="field_value_user"),
        ),
        migrations.AddIndex(
            model_name="taskfieldvalue",
            index=models.Index(fields=["field", "date"], name="field_value_date"),
        ),
        migrations.AddIndex(
            model_name="taskfieldvalue",
            index=models.Index(fields=["field", "number"], name="field_value_number"),
        ),
        migrations.AddConstraint(
            model_name="taskfieldvalue",
            constraint=models.UniqueConstraint(
                fields=("task", "field"), name="task_field_value_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskfieldvalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("date__isnull", True),
                        ("number__isnull", True),
                        ("option__isnull", True),
                        ("text__isnull", False),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("date__isnull", True),
                        ("number__isnull", False),
                        ("option__isnull", True),
                        ("text__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("date__isnull", False),
                        ("number__isnull", True),
                        ("option__isnull", True),
                        ("text__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("date__isnull", True),
                        ("number__isnull", True),
                        ("option__isnull", False),
                        ("text__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("date__isnull", True),
                        ("number__isnull", True),
                        ("option__isnull", True),
                        ("text__isnull", True),
                        ("user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="task_field_value_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskfieldvalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("number__isnull", True),
                    models.Q(("number__gte", 0), ("number__lte", 1000000000)),
                    _connector="OR",
                ),
                name="task_field_value_number_range",
            ),
        ),
    ]
