# Generated by Django 5.2.18 on 2026-10-09 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_epic_dates"),
        ("projects", "0003_custom_fields"),
        ("tasks", "0002_fields_dependencies_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project", "due_date"], name="task_due"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project", "start_date"], name="task_start"),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_date__isnull", True),
                    ("due_date__isnull", True),
                    ("start_date__lte", models.F("due_date")),
                    _connector="OR",
                ),
                name="task_dates_ordered",
            ),
        ),
    ]
