"""Object storage behind one interface.

- R2Storage: Cloudflare R2 (S3 API via boto3). Presigned PUT for uploads, HEAD + ranged GET to
  verify them, presigned GET with forced Content-Type / Content-Disposition for downloads.
- LocalStorage: files on disk with signed, expiring URLs served by this API (development without R2).
- FakeStorage: in memory, for tests.

Keys are generated by the caller (never from user file names).
"""

from __future__ import annotations

import datetime as dt
import threading
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Protocol
from urllib.parse import quote

from django.conf import settings
from django.core import signing
from django.utils import timezone


@dataclass(frozen=True)
class ObjectInfo:
    size: int
    content_type: str


class StorageBackend(Protocol):
    def presigned_put(self, key: str, content_type: str, expires: int) -> tuple[str, dict[str, str]]: ...

    def head(self, key: str) -> ObjectInfo | None: ...

    def read_prefix(self, key: str, length: int) -> bytes: ...

    def presigned_get(self, key: str, *, file_name: str, content_type: str, inline: bool, expires: int) -> str: ...

    def delete(self, key: str) -> None: ...

    def put(self, key: str, data: bytes, content_type: str) -> None:
        """Server-side write (import parsed files and error reports)."""
        ...


def content_disposition(file_name: str, inline: bool) -> str:
    ascii_name = file_name.encode("ascii", "ignore").decode().replace('"', "").replace("\\", "") or "file"
    kind = "inline" if inline else "attachment"
    return f"{kind}; filename=\"{ascii_name}\"; filename*=UTF-8''{quote(file_name)}"


def expires_at(seconds: int) -> dt.datetime:
    return timezone.now() + dt.timedelta(seconds=seconds)


class R2Storage:
    def __init__(self) -> None:
        import boto3
        from botocore.config import Config

        endpoint = settings.R2_ENDPOINT_URL or f"https://{settings.R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
        self.bucket = settings.R2_BUCKET
        self.client = boto3.client(
            "s3",
            endpoint_url=endpoint,
            aws_access_key_id=settings.R2_ACCESS_KEY_ID,
            aws_secret_access_key=settings.R2_SECRET_ACCESS_KEY,
            region_name="auto",
            config=Config(signature_version="s3v4", retries={"max_attempts": 3}),
        )

    def presigned_put(self, key: str, content_type: str, expires: int) -> tuple[str, dict[str, str]]:
        url = self.client.generate_presigned_url(
            "put_object",
            Params={"Bucket": self.bucket, "Key": key, "ContentType": content_type},
            ExpiresIn=expires,
        )
        return url, {"Content-Type": content_type}

    def head(self, key: str) -> ObjectInfo | None:
        from botocore.exceptions import ClientError

        try:
            meta = self.client.head_object(Bucket=self.bucket, Key=key)
        except ClientError:
            return None
        return ObjectInfo(size=int(meta["ContentLength"]), content_type=meta.get("ContentType", ""))

    def read_prefix(self, key: str, length: int) -> bytes:
        obj = self.client.get_object(Bucket=self.bucket, Key=key, Range=f"bytes=0-{length - 1}")
        return obj["Body"].read()

    def presigned_get(self, key: str, *, file_name: str, content_type: str, inline: bool, expires: int) -> str:
        return self.client.generate_presigned_url(
            "get_object",
            Params={
                "Bucket": self.bucket,
                "Key": key,
                "ResponseContentType": content_type,
                "ResponseContentDisposition": content_disposition(file_name, inline),
                "ResponseCacheControl": "private, max-age=60",
            },
            ExpiresIn=expires,
        )

    def delete(self, key: str) -> None:
        self.client.delete_object(Bucket=self.bucket, Key=key)

    def put(self, key: str, data: bytes, content_type: str) -> None:
        self.client.put_object(Bucket=self.bucket, Key=key, Body=data, ContentType=content_type)


class FakeStorage:
    """In-memory storage for tests. `put()` stands in for the browser's PUT to the signed URL."""

    def __init__(self) -> None:
        self.objects: dict[str, tuple[bytes, str]] = {}
        self.lock = threading.Lock()

    def put(self, key: str, data: bytes, content_type: str) -> None:
        with self.lock:
            self.objects[key] = (data, content_type)

    def presigned_put(self, key: str, content_type: str, expires: int) -> tuple[str, dict[str, str]]:
        return f"https://storage.test/upload/{quote(key)}?expires={expires}", {"Content-Type": content_type}

    def head(self, key: str) -> ObjectInfo | None:
        item = self.objects.get(key)
        return ObjectInfo(len(item[0]), item[1]) if item else None

    def read_prefix(self, key: str, length: int) -> bytes:
        return self.objects[key][0][:length]

    def presigned_get(self, key: str, *, file_name: str, content_type: str, inline: bool, expires: int) -> str:
        disposition = quote(content_disposition(file_name, inline))
        return (
            f"https://storage.test/download/{quote(key)}?type={quote(content_type)}&cd={disposition}&expires={expires}"
        )

    def delete(self, key: str) -> None:
        with self.lock:
            self.objects.pop(key, None)


class LocalStorage:
    """Development only: files under MEDIA_ROOT, uploaded and downloaded through signed URLs."""

    salt = "lightex.local-storage"

    def __init__(self) -> None:
        self.root = Path(settings.MEDIA_ROOT) / "attachments"
        self.root.mkdir(parents=True, exist_ok=True)

    def path(self, key: str) -> Path:
        target = (self.root / key).resolve()
        if self.root.resolve() not in target.parents:
            raise ValueError("Invalid storage key")
        return target

    def _url(self, action: str, payload: dict) -> str:
        token = signing.dumps(payload, salt=f"{self.salt}.{action}")
        return f"{settings.API_PUBLIC_URL}/api/v1/storage/{action}/{token}"

    @classmethod
    def verify(cls, action: str, token: str, max_age: int) -> dict:
        return signing.loads(token, salt=f"{cls.salt}.{action}", max_age=max_age)

    def write(self, key: str, data: bytes, content_type: str) -> None:
        target = self.path(key)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        target.with_suffix(target.suffix + ".type").write_text(content_type)

    def put(self, key: str, data: bytes, content_type: str) -> None:
        self.write(key, data, content_type)

    def presigned_put(self, key: str, content_type: str, expires: int) -> tuple[str, dict[str, str]]:
        return self._url("upload", {"k": key, "t": content_type}), {"Content-Type": content_type}

    def head(self, key: str) -> ObjectInfo | None:
        target = self.path(key)
        if not target.exists():
            return None
        meta = target.with_suffix(target.suffix + ".type")
        return ObjectInfo(target.stat().st_size, meta.read_text() if meta.exists() else "")

    def read_prefix(self, key: str, length: int) -> bytes:
        with self.path(key).open("rb") as fh:
            return fh.read(length)

    def presigned_get(self, key: str, *, file_name: str, content_type: str, inline: bool, expires: int) -> str:
        return self._url("download", {"k": key, "t": content_type, "n": file_name, "i": inline})

    def delete(self, key: str) -> None:
        target = self.path(key)
        for p in (target, target.with_suffix(target.suffix + ".type")):
            if p.exists():
                p.unlink()


@lru_cache(maxsize=1)
def get_storage() -> StorageBackend:
    backend = settings.STORAGE_BACKEND
    if backend == "r2":
        return R2Storage()
    if backend == "local":
        return LocalStorage()
    return FakeStorage()
