# Generated by Django 5.2.18 on 2026-10-09 10:35

import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("shared", "Shared"), ("personal", "Personal")],
                        max_length=8,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("burndown", "Burndown"),
                            ("my_tasks", "My tasks"),
                            ("objectives", "Objective progress"),
                            ("workload", "Workload by person"),
                            ("velocity", "Velocity"),
                            ("activity", "Recent activity"),
                        ],
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("w", models.PositiveSmallIntegerField()),
                ("h", models.PositiveSmallIntegerField()),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["project", "visibility"], name="dashboard_project_vis"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["project", "owner"], name="dashboard_project_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                models.F("project"),
                models.F("owner"),
                django.db.models.functions.text.Lower("name"),
                name="dashboard_name_unique_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardwidget",
            constraint=models.UniqueConstraint(
                fields=("dashboard", "type"), name="dashboard_widget_type_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardwidget",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("dashboard", "position"),
                name="dashboard_widget_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardwidget",
            constraint=models.CheckConstraint(
                condition=models.Q(("w__gte", 3), ("w__lte", 12)),
                name="dashboard_widget_w_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardwidget",
            constraint=models.CheckConstraint(
                condition=models.Q(("h__gte", 1), ("h__lte", 4)),
                name="dashboard_widget_h_range",
            ),
        ),
    ]
