# Generated by Django 5.2.18 on 2026-10-07 18:43

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planning", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprintscopechange",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tasks.task",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lte", models.F("due_date"))),
                name="milestone_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="epic",
            constraint=models.UniqueConstraint(
                models.F("project"),
                django.db.models.functions.text.Lower("name"),
                name="epic_name_unique_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="sprint",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="sprint_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sprint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("project",),
                name="sprint_one_active_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="sprint",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lte", models.F("end_date"))),
                name="sprint_dates_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="sprintscopechange",
            index=models.Index(fields=["sprint", "at"], name="scope_change_sprint_at"),
        ),
    ]
