# Generated by Django 5.2.18 on 2026-10-09 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_initial"),
        ("projects", "0003_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="epic",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="epic",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="epic",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("due_date__isnull", True), ("start_date__isnull", True)),
                    models.Q(
                        ("due_date__isnull", False),
                        ("start_date__isnull", False),
                        ("start_date__lte", models.F("due_date")),
                    ),
                    _connector="OR",
                ),
                name="epic_dates_ordered",
            ),
        ),
    ]
