# Generated by Django 5.2.18 on 2026-10-09 09:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planning", "0003_epic_dates"),
        ("projects", "0003_custom_fields"),
        ("tasks", "0003_task_start_date"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("csv", "CSV"), ("jira", "Jira")], max_length=8
                    ),
                ),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("generic", "Generic"),
                            ("jira", "Jira"),
                            ("linear", "Linear"),
                            ("asana", "Asana"),
                        ],
                        default="generic",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("cancel_requested", models.BooleanField(default=False)),
                ("file_name", models.CharField(max_length=120)),
                ("file_size", models.PositiveIntegerField()),
                ("source_key", models.CharField(max_length=300, unique=True)),
                (
                    "parsed_key",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "report_key",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("encoding", models.CharField(blank=True, default="", max_length=16)),
                ("delimiter", models.CharField(blank=True, default="", max_length=1)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("column_count", models.PositiveIntegerField(default=0)),
                ("analysis", models.JSONField(blank=True, null=True)),
                ("mapping", models.JSONField(blank=True, null=True)),
                ("mapping_revision", models.PositiveIntegerField(default=0)),
                ("validation", models.JSONField(blank=True, null=True)),
                ("phase", models.CharField(blank=True, default="", max_length=10)),
                ("number_base", models.PositiveIntegerField(blank=True, null=True)),
                ("planned_tasks", models.PositiveIntegerField(default=0)),
                ("cursor", models.PositiveIntegerField(default=0)),
                ("setup", models.JSONField(blank=True, default=dict)),
                ("imported", models.PositiveIntegerField(default=0)),
                ("epics_created", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("warnings", models.PositiveIntegerField(default=0)),
                ("labels_created", models.PositiveIntegerField(default=0)),
                ("options_created", models.PositiveIntegerField(default=0)),
                ("first_key", models.CharField(blank=True, default="", max_length=24)),
                ("last_key", models.CharField(blank=True, default="", max_length=24)),
                ("recent", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, default="", max_length=40)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="projects.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row", models.PositiveIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("epic", "Epic"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=8,
                    ),
                ),
                ("refs", models.JSONField(blank=True, default=list)),
                ("issues", models.JSONField(blank=True, default=list)),
                (
                    "epic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="planning.epic",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="imports.importjob",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["project", "-created_at"], name="import_project_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["status", "heartbeat_at"], name="import_recovery"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["expires_at"], name="import_expiry"),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=("project",),
                name="import_one_active_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_count__lte", 5000)), name="import_row_cap"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(fields=["job", "outcome"], name="import_row_outcome"),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("job", "row"), name="import_row_unique"
            ),
        ),
    ]
